apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: pliro-dev
spec:
  serviceName: "mongodb"
  selector:
    matchLabels:
      app: mongodb
  replicas: 1 
  template:
    metadata:
      labels:
        app: mongodb
    spec:   
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "app"
        effect: "NoSchedule"   
      containers:
      - image: mongo:3.4
        name: mongodb
        ports:
        - containerPort: 27017
          name: tcp
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-pvc      
        resources: {}          
      - image: stakater/mongo-backup-restore-s3:0.0.4
        name: mongodb-backup-restore
        volumeMounts:
        - mountPath: /backup
          name: mongodb-pvc    
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: aws_secret_access_key
        - name: BUCKET
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: bucket
        - name: BACKUP_FOLDER
          value: "mongo/"
        - name: MONGODB_HOST
          value: "localhost"
        - name: MONGODB_PORT
          value: "27017"
#        - name: MONGODB_USER   Default not set
#          value: ""
#        - name: MONGODB_PASS   Default not set
#          value: ""
#        - name: MONGODB_DB     Not specified. so dump all dbs
#          value: ""
        - name: CRON_TIME
          value: "0 */1 * * *"
        - name: TZ
          value: "US/Eastern"
        - name: CRON_TZ
          value: "US/Eastern"
        - name: INIT_BACKUP
          value: "true"
        - name: INIT_RESTORE
          value: "true"
#        - name: DISABLE_CRON
#          value: "false"
      restartPolicy: Always

  volumeClaimTemplates:
  - metadata:
      name: mongodb-pvc
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: efs
      resources:
        requests:
          storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongodb-svc
  namespace: pliro-dev
spec:
  ports:
  - name: "mongo-port"
    port: 27017
    targetPort: 27017
  selector:
    app: mongodb